/*
 * Lithosurfer API: Geochem model
 * Please have a look at the <a href=\"https://docs.google.com/presentation/d/1XcjHiopwNzasUvwC_7UZlkou82tfstEdqGZxqXITV3s/edit?usp=sharing\">High Level Docs</a> for getting the whole picture.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lithosurfer.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelGeneratedFromSwagger;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClusterDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-07T06:47:05.458Z")
public class ClusterDTO {
  @SerializedName("centerOfDistancesLat")
  private Float centerOfDistancesLat = null;

  @SerializedName("centerOfDistancesLon")
  private Float centerOfDistancesLon = null;

  @SerializedName("leftBound")
  private Float leftBound = null;

  @SerializedName("locationCount")
  private Integer locationCount = null;

  @SerializedName("lowerBound")
  private Float lowerBound = null;

  @SerializedName("rightBound")
  private Float rightBound = null;

  @SerializedName("upperBound")
  private Float upperBound = null;

  @SerializedName("zoomLevel")
  private Integer zoomLevel = null;

  public ClusterDTO centerOfDistancesLat(Float centerOfDistancesLat) {
    this.centerOfDistancesLat = centerOfDistancesLat;
    return this;
  }

   /**
   * Get centerOfDistancesLat
   * @return centerOfDistancesLat
  **/
  @ApiModelProperty(value = "")
  public Float getCenterOfDistancesLat() {
    return centerOfDistancesLat;
  }

  public void setCenterOfDistancesLat(Float centerOfDistancesLat) {
    this.centerOfDistancesLat = centerOfDistancesLat;
  }

  public ClusterDTO centerOfDistancesLon(Float centerOfDistancesLon) {
    this.centerOfDistancesLon = centerOfDistancesLon;
    return this;
  }

   /**
   * Get centerOfDistancesLon
   * @return centerOfDistancesLon
  **/
  @ApiModelProperty(value = "")
  public Float getCenterOfDistancesLon() {
    return centerOfDistancesLon;
  }

  public void setCenterOfDistancesLon(Float centerOfDistancesLon) {
    this.centerOfDistancesLon = centerOfDistancesLon;
  }

  public ClusterDTO leftBound(Float leftBound) {
    this.leftBound = leftBound;
    return this;
  }

   /**
   * Get leftBound
   * @return leftBound
  **/
  @ApiModelProperty(value = "")
  public Float getLeftBound() {
    return leftBound;
  }

  public void setLeftBound(Float leftBound) {
    this.leftBound = leftBound;
  }

  public ClusterDTO locationCount(Integer locationCount) {
    this.locationCount = locationCount;
    return this;
  }

   /**
   * Get locationCount
   * @return locationCount
  **/
  @ApiModelProperty(value = "")
  public Integer getLocationCount() {
    return locationCount;
  }

  public void setLocationCount(Integer locationCount) {
    this.locationCount = locationCount;
  }

  public ClusterDTO lowerBound(Float lowerBound) {
    this.lowerBound = lowerBound;
    return this;
  }

   /**
   * Get lowerBound
   * @return lowerBound
  **/
  @ApiModelProperty(value = "")
  public Float getLowerBound() {
    return lowerBound;
  }

  public void setLowerBound(Float lowerBound) {
    this.lowerBound = lowerBound;
  }

  public ClusterDTO rightBound(Float rightBound) {
    this.rightBound = rightBound;
    return this;
  }

   /**
   * Get rightBound
   * @return rightBound
  **/
  @ApiModelProperty(value = "")
  public Float getRightBound() {
    return rightBound;
  }

  public void setRightBound(Float rightBound) {
    this.rightBound = rightBound;
  }

  public ClusterDTO upperBound(Float upperBound) {
    this.upperBound = upperBound;
    return this;
  }

   /**
   * Get upperBound
   * @return upperBound
  **/
  @ApiModelProperty(value = "")
  public Float getUpperBound() {
    return upperBound;
  }

  public void setUpperBound(Float upperBound) {
    this.upperBound = upperBound;
  }

  public ClusterDTO zoomLevel(Integer zoomLevel) {
    this.zoomLevel = zoomLevel;
    return this;
  }

   /**
   * Get zoomLevel
   * @return zoomLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getZoomLevel() {
    return zoomLevel;
  }

  public void setZoomLevel(Integer zoomLevel) {
    this.zoomLevel = zoomLevel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterDTO clusterDTO = (ClusterDTO) o;
    return Objects.equals(this.centerOfDistancesLat, clusterDTO.centerOfDistancesLat) &&
        Objects.equals(this.centerOfDistancesLon, clusterDTO.centerOfDistancesLon) &&
        Objects.equals(this.leftBound, clusterDTO.leftBound) &&
        Objects.equals(this.locationCount, clusterDTO.locationCount) &&
        Objects.equals(this.lowerBound, clusterDTO.lowerBound) &&
        Objects.equals(this.rightBound, clusterDTO.rightBound) &&
        Objects.equals(this.upperBound, clusterDTO.upperBound) &&
        Objects.equals(this.zoomLevel, clusterDTO.zoomLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(centerOfDistancesLat, centerOfDistancesLon, leftBound, locationCount, lowerBound, rightBound, upperBound, zoomLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterDTO {\n");
    
    sb.append("    centerOfDistancesLat: ").append(toIndentedString(centerOfDistancesLat)).append("\n");
    sb.append("    centerOfDistancesLon: ").append(toIndentedString(centerOfDistancesLon)).append("\n");
    sb.append("    leftBound: ").append(toIndentedString(leftBound)).append("\n");
    sb.append("    locationCount: ").append(toIndentedString(locationCount)).append("\n");
    sb.append("    lowerBound: ").append(toIndentedString(lowerBound)).append("\n");
    sb.append("    rightBound: ").append(toIndentedString(rightBound)).append("\n");
    sb.append("    upperBound: ").append(toIndentedString(upperBound)).append("\n");
    sb.append("    zoomLevel: ").append(toIndentedString(zoomLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

