/*
 * Lithosurfer API: Geochem model
 * Please have a look at the <a href=\"https://docs.google.com/presentation/d/1XcjHiopwNzasUvwC_7UZlkou82tfstEdqGZxqXITV3s/edit?usp=sharing\">High Level Docs</a> for getting the whole picture.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lithosurfer.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelGeneratedFromSwagger;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ElementalConcentrationDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-07T06:47:05.458Z")
public class ElementalConcentrationDTO {
  @SerializedName("aliquotName")
  private String aliquotName = null;

  @SerializedName("concentration")
  private Float concentration = null;

  @SerializedName("elementId")
  private Long elementId = null;

  @SerializedName("elementName")
  private String elementName = null;

  @SerializedName("error")
  private Float error = null;

  @SerializedName("gcdataPointId")
  private Long gcdataPointId = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("isotopeId")
  private Long isotopeId = null;

  @SerializedName("isotopeName")
  private String isotopeName = null;

  @SerializedName("measuredMass")
  private Integer measuredMass = null;

  @SerializedName("relativeOperatorId")
  private Long relativeOperatorId = null;

  @SerializedName("relativeOperatorName")
  private String relativeOperatorName = null;

  @SerializedName("spotID")
  private String spotID = null;

  public ElementalConcentrationDTO aliquotName(String aliquotName) {
    this.aliquotName = aliquotName;
    return this;
  }

   /**
   * Get aliquotName
   * @return aliquotName
  **/
  @ApiModelProperty(value = "")
  public String getAliquotName() {
    return aliquotName;
  }

  public void setAliquotName(String aliquotName) {
    this.aliquotName = aliquotName;
  }

  public ElementalConcentrationDTO concentration(Float concentration) {
    this.concentration = concentration;
    return this;
  }

   /**
   * Get concentration
   * @return concentration
  **/
  @ApiModelProperty(value = "")
  public Float getConcentration() {
    return concentration;
  }

  public void setConcentration(Float concentration) {
    this.concentration = concentration;
  }

  public ElementalConcentrationDTO elementId(Long elementId) {
    this.elementId = elementId;
    return this;
  }

   /**
   * Get elementId
   * @return elementId
  **/
  @ApiModelProperty(value = "")
  public Long getElementId() {
    return elementId;
  }

  public void setElementId(Long elementId) {
    this.elementId = elementId;
  }

  public ElementalConcentrationDTO elementName(String elementName) {
    this.elementName = elementName;
    return this;
  }

   /**
   * Get elementName
   * @return elementName
  **/
  @ApiModelProperty(value = "")
  public String getElementName() {
    return elementName;
  }

  public void setElementName(String elementName) {
    this.elementName = elementName;
  }

  public ElementalConcentrationDTO error(Float error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Float getError() {
    return error;
  }

  public void setError(Float error) {
    this.error = error;
  }

  public ElementalConcentrationDTO gcdataPointId(Long gcdataPointId) {
    this.gcdataPointId = gcdataPointId;
    return this;
  }

   /**
   * Get gcdataPointId
   * @return gcdataPointId
  **/
  @ApiModelProperty(value = "")
  public Long getGcdataPointId() {
    return gcdataPointId;
  }

  public void setGcdataPointId(Long gcdataPointId) {
    this.gcdataPointId = gcdataPointId;
  }

  public ElementalConcentrationDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ElementalConcentrationDTO isotopeId(Long isotopeId) {
    this.isotopeId = isotopeId;
    return this;
  }

   /**
   * Get isotopeId
   * @return isotopeId
  **/
  @ApiModelProperty(value = "")
  public Long getIsotopeId() {
    return isotopeId;
  }

  public void setIsotopeId(Long isotopeId) {
    this.isotopeId = isotopeId;
  }

  public ElementalConcentrationDTO isotopeName(String isotopeName) {
    this.isotopeName = isotopeName;
    return this;
  }

   /**
   * Get isotopeName
   * @return isotopeName
  **/
  @ApiModelProperty(value = "")
  public String getIsotopeName() {
    return isotopeName;
  }

  public void setIsotopeName(String isotopeName) {
    this.isotopeName = isotopeName;
  }

  public ElementalConcentrationDTO measuredMass(Integer measuredMass) {
    this.measuredMass = measuredMass;
    return this;
  }

   /**
   * Get measuredMass
   * @return measuredMass
  **/
  @ApiModelProperty(value = "")
  public Integer getMeasuredMass() {
    return measuredMass;
  }

  public void setMeasuredMass(Integer measuredMass) {
    this.measuredMass = measuredMass;
  }

  public ElementalConcentrationDTO relativeOperatorId(Long relativeOperatorId) {
    this.relativeOperatorId = relativeOperatorId;
    return this;
  }

   /**
   * Get relativeOperatorId
   * @return relativeOperatorId
  **/
  @ApiModelProperty(value = "")
  public Long getRelativeOperatorId() {
    return relativeOperatorId;
  }

  public void setRelativeOperatorId(Long relativeOperatorId) {
    this.relativeOperatorId = relativeOperatorId;
  }

  public ElementalConcentrationDTO relativeOperatorName(String relativeOperatorName) {
    this.relativeOperatorName = relativeOperatorName;
    return this;
  }

   /**
   * Get relativeOperatorName
   * @return relativeOperatorName
  **/
  @ApiModelProperty(value = "")
  public String getRelativeOperatorName() {
    return relativeOperatorName;
  }

  public void setRelativeOperatorName(String relativeOperatorName) {
    this.relativeOperatorName = relativeOperatorName;
  }

  public ElementalConcentrationDTO spotID(String spotID) {
    this.spotID = spotID;
    return this;
  }

   /**
   * Get spotID
   * @return spotID
  **/
  @ApiModelProperty(value = "")
  public String getSpotID() {
    return spotID;
  }

  public void setSpotID(String spotID) {
    this.spotID = spotID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementalConcentrationDTO elementalConcentrationDTO = (ElementalConcentrationDTO) o;
    return Objects.equals(this.aliquotName, elementalConcentrationDTO.aliquotName) &&
        Objects.equals(this.concentration, elementalConcentrationDTO.concentration) &&
        Objects.equals(this.elementId, elementalConcentrationDTO.elementId) &&
        Objects.equals(this.elementName, elementalConcentrationDTO.elementName) &&
        Objects.equals(this.error, elementalConcentrationDTO.error) &&
        Objects.equals(this.gcdataPointId, elementalConcentrationDTO.gcdataPointId) &&
        Objects.equals(this.id, elementalConcentrationDTO.id) &&
        Objects.equals(this.isotopeId, elementalConcentrationDTO.isotopeId) &&
        Objects.equals(this.isotopeName, elementalConcentrationDTO.isotopeName) &&
        Objects.equals(this.measuredMass, elementalConcentrationDTO.measuredMass) &&
        Objects.equals(this.relativeOperatorId, elementalConcentrationDTO.relativeOperatorId) &&
        Objects.equals(this.relativeOperatorName, elementalConcentrationDTO.relativeOperatorName) &&
        Objects.equals(this.spotID, elementalConcentrationDTO.spotID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aliquotName, concentration, elementId, elementName, error, gcdataPointId, id, isotopeId, isotopeName, measuredMass, relativeOperatorId, relativeOperatorName, spotID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElementalConcentrationDTO {\n");
    
    sb.append("    aliquotName: ").append(toIndentedString(aliquotName)).append("\n");
    sb.append("    concentration: ").append(toIndentedString(concentration)).append("\n");
    sb.append("    elementId: ").append(toIndentedString(elementId)).append("\n");
    sb.append("    elementName: ").append(toIndentedString(elementName)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    gcdataPointId: ").append(toIndentedString(gcdataPointId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isotopeId: ").append(toIndentedString(isotopeId)).append("\n");
    sb.append("    isotopeName: ").append(toIndentedString(isotopeName)).append("\n");
    sb.append("    measuredMass: ").append(toIndentedString(measuredMass)).append("\n");
    sb.append("    relativeOperatorId: ").append(toIndentedString(relativeOperatorId)).append("\n");
    sb.append("    relativeOperatorName: ").append(toIndentedString(relativeOperatorName)).append("\n");
    sb.append("    spotID: ").append(toIndentedString(spotID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

