/*
 * Lithosurfer API: Geochem model
 * Please have a look at the <a href=\"https://docs.google.com/presentation/d/1XcjHiopwNzasUvwC_7UZlkou82tfstEdqGZxqXITV3s/edit?usp=sharing\">High Level Docs</a> for getting the whole picture.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lithosurfer.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelGeneratedFromSwagger;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import modelGeneratedFromSwagger.DataPointDTO;
import modelGeneratedFromSwagger.DataPointMetaDTO;
import modelGeneratedFromSwagger.GCDataPointDTO;
import modelGeneratedFromSwagger.ICPMSLithoDTO;
import modelGeneratedFromSwagger.LAICPMSDTO;

import java.io.IOException;

/**
 * GCDataPointLithoDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-07T06:47:05.458Z")
public class GCDataPointLithoDTO {
  @SerializedName("countElementalConcentrations")
  private Integer countElementalConcentrations = null;

  @SerializedName("countOxideConcentrations")
  private Integer countOxideConcentrations = null;

  @SerializedName("dataPointDTO")
  private DataPointDTO dataPointDTO = null;

  @SerializedName("dataPointId")
  private Long dataPointId = null;

  @SerializedName("dataPointMetaDTO")
  private DataPointMetaDTO dataPointMetaDTO = null;

  @SerializedName("gcdataPointDTO")
  private GCDataPointDTO gcdataPointDTO = null;

  @SerializedName("iCPMSLithoDTO")
  private ICPMSLithoDTO iCPMSLithoDTO = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("laicpmsDTO")
  private LAICPMSDTO laicpmsDTO = null;

  public GCDataPointLithoDTO countElementalConcentrations(Integer countElementalConcentrations) {
    this.countElementalConcentrations = countElementalConcentrations;
    return this;
  }

   /**
   * Get countElementalConcentrations
   * @return countElementalConcentrations
  **/
  @ApiModelProperty(value = "")
  public Integer getCountElementalConcentrations() {
    return countElementalConcentrations;
  }

  public void setCountElementalConcentrations(Integer countElementalConcentrations) {
    this.countElementalConcentrations = countElementalConcentrations;
  }

  public GCDataPointLithoDTO countOxideConcentrations(Integer countOxideConcentrations) {
    this.countOxideConcentrations = countOxideConcentrations;
    return this;
  }

   /**
   * Get countOxideConcentrations
   * @return countOxideConcentrations
  **/
  @ApiModelProperty(value = "")
  public Integer getCountOxideConcentrations() {
    return countOxideConcentrations;
  }

  public void setCountOxideConcentrations(Integer countOxideConcentrations) {
    this.countOxideConcentrations = countOxideConcentrations;
  }

  public GCDataPointLithoDTO dataPointDTO(DataPointDTO dataPointDTO) {
    this.dataPointDTO = dataPointDTO;
    return this;
  }

   /**
   * Get dataPointDTO
   * @return dataPointDTO
  **/
  @ApiModelProperty(value = "")
  public DataPointDTO getDataPointDTO() {
    return dataPointDTO;
  }

  public void setDataPointDTO(DataPointDTO dataPointDTO) {
    this.dataPointDTO = dataPointDTO;
  }

  public GCDataPointLithoDTO dataPointId(Long dataPointId) {
    this.dataPointId = dataPointId;
    return this;
  }

   /**
   * Get dataPointId
   * @return dataPointId
  **/
  @ApiModelProperty(value = "")
  public Long getDataPointId() {
    return dataPointId;
  }

  public void setDataPointId(Long dataPointId) {
    this.dataPointId = dataPointId;
  }

  public GCDataPointLithoDTO dataPointMetaDTO(DataPointMetaDTO dataPointMetaDTO) {
    this.dataPointMetaDTO = dataPointMetaDTO;
    return this;
  }

   /**
   * Get dataPointMetaDTO
   * @return dataPointMetaDTO
  **/
  @ApiModelProperty(value = "")
  public DataPointMetaDTO getDataPointMetaDTO() {
    return dataPointMetaDTO;
  }

  public void setDataPointMetaDTO(DataPointMetaDTO dataPointMetaDTO) {
    this.dataPointMetaDTO = dataPointMetaDTO;
  }

  public GCDataPointLithoDTO gcdataPointDTO(GCDataPointDTO gcdataPointDTO) {
    this.gcdataPointDTO = gcdataPointDTO;
    return this;
  }

   /**
   * Get gcdataPointDTO
   * @return gcdataPointDTO
  **/
  @ApiModelProperty(value = "")
  public GCDataPointDTO getGcdataPointDTO() {
    return gcdataPointDTO;
  }

  public void setGcdataPointDTO(GCDataPointDTO gcdataPointDTO) {
    this.gcdataPointDTO = gcdataPointDTO;
  }

  public GCDataPointLithoDTO iCPMSLithoDTO(ICPMSLithoDTO iCPMSLithoDTO) {
    this.iCPMSLithoDTO = iCPMSLithoDTO;
    return this;
  }

   /**
   * Get iCPMSLithoDTO
   * @return iCPMSLithoDTO
  **/
  @ApiModelProperty(value = "")
  public ICPMSLithoDTO getICPMSLithoDTO() {
    return iCPMSLithoDTO;
  }

  public void setICPMSLithoDTO(ICPMSLithoDTO iCPMSLithoDTO) {
    this.iCPMSLithoDTO = iCPMSLithoDTO;
  }

  public GCDataPointLithoDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public GCDataPointLithoDTO laicpmsDTO(LAICPMSDTO laicpmsDTO) {
    this.laicpmsDTO = laicpmsDTO;
    return this;
  }

   /**
   * Get laicpmsDTO
   * @return laicpmsDTO
  **/
  @ApiModelProperty(value = "")
  public LAICPMSDTO getLaicpmsDTO() {
    return laicpmsDTO;
  }

  public void setLaicpmsDTO(LAICPMSDTO laicpmsDTO) {
    this.laicpmsDTO = laicpmsDTO;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GCDataPointLithoDTO gcDataPointLithoDTO = (GCDataPointLithoDTO) o;
    return Objects.equals(this.countElementalConcentrations, gcDataPointLithoDTO.countElementalConcentrations) &&
        Objects.equals(this.countOxideConcentrations, gcDataPointLithoDTO.countOxideConcentrations) &&
        Objects.equals(this.dataPointDTO, gcDataPointLithoDTO.dataPointDTO) &&
        Objects.equals(this.dataPointId, gcDataPointLithoDTO.dataPointId) &&
        Objects.equals(this.dataPointMetaDTO, gcDataPointLithoDTO.dataPointMetaDTO) &&
        Objects.equals(this.gcdataPointDTO, gcDataPointLithoDTO.gcdataPointDTO) &&
        Objects.equals(this.iCPMSLithoDTO, gcDataPointLithoDTO.iCPMSLithoDTO) &&
        Objects.equals(this.id, gcDataPointLithoDTO.id) &&
        Objects.equals(this.laicpmsDTO, gcDataPointLithoDTO.laicpmsDTO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countElementalConcentrations, countOxideConcentrations, dataPointDTO, dataPointId, dataPointMetaDTO, gcdataPointDTO, iCPMSLithoDTO, id, laicpmsDTO);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GCDataPointLithoDTO {\n");
    
    sb.append("    countElementalConcentrations: ").append(toIndentedString(countElementalConcentrations)).append("\n");
    sb.append("    countOxideConcentrations: ").append(toIndentedString(countOxideConcentrations)).append("\n");
    sb.append("    dataPointDTO: ").append(toIndentedString(dataPointDTO)).append("\n");
    sb.append("    dataPointId: ").append(toIndentedString(dataPointId)).append("\n");
    sb.append("    dataPointMetaDTO: ").append(toIndentedString(dataPointMetaDTO)).append("\n");
    sb.append("    gcdataPointDTO: ").append(toIndentedString(gcdataPointDTO)).append("\n");
    sb.append("    iCPMSLithoDTO: ").append(toIndentedString(iCPMSLithoDTO)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    laicpmsDTO: ").append(toIndentedString(laicpmsDTO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

