/*
 * Lithosurfer API: Geochem model
 * Please have a look at the <a href=\"https://docs.google.com/presentation/d/1XcjHiopwNzasUvwC_7UZlkou82tfstEdqGZxqXITV3s/edit?usp=sharing\">High Level Docs</a> for getting the whole picture.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lithosurfer.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelGeneratedFromSwagger;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import modelGeneratedFromSwagger.HRICPMSMetadataDTO;
import modelGeneratedFromSwagger.ICPMSMSMetadataDTO;
import modelGeneratedFromSwagger.ICPMSMetadataDTO;
import modelGeneratedFromSwagger.LaserMetadataDTO;
import modelGeneratedFromSwagger.MCICPMSMetadataDTO;
import modelGeneratedFromSwagger.QICPMSMetadataDTO;
import modelGeneratedFromSwagger.SolutionOtherMetadataDTO;

import java.io.IOException;

/**
 * ICPMSLithoDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-07T06:47:05.458Z")
public class ICPMSLithoDTO {
  @SerializedName("hRICPMSMetadataDTO")
  private HRICPMSMetadataDTO hRICPMSMetadataDTO = null;

  @SerializedName("iCPMSMSMetadataDTO")
  private ICPMSMSMetadataDTO iCPMSMSMetadataDTO = null;

  @SerializedName("iCPMSMetadataDTO")
  private ICPMSMetadataDTO iCPMSMetadataDTO = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("laserMetadataDTO")
  private LaserMetadataDTO laserMetadataDTO = null;

  @SerializedName("mCICPMSMetadataDTO")
  private MCICPMSMetadataDTO mCICPMSMetadataDTO = null;

  @SerializedName("qICPMSMetadataDTO")
  private QICPMSMetadataDTO qICPMSMetadataDTO = null;

  @SerializedName("solutionOtherMetadataDTO")
  private SolutionOtherMetadataDTO solutionOtherMetadataDTO = null;

  public ICPMSLithoDTO hRICPMSMetadataDTO(HRICPMSMetadataDTO hRICPMSMetadataDTO) {
    this.hRICPMSMetadataDTO = hRICPMSMetadataDTO;
    return this;
  }

   /**
   * Get hRICPMSMetadataDTO
   * @return hRICPMSMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public HRICPMSMetadataDTO getHRICPMSMetadataDTO() {
    return hRICPMSMetadataDTO;
  }

  public void setHRICPMSMetadataDTO(HRICPMSMetadataDTO hRICPMSMetadataDTO) {
    this.hRICPMSMetadataDTO = hRICPMSMetadataDTO;
  }

  public ICPMSLithoDTO iCPMSMSMetadataDTO(ICPMSMSMetadataDTO iCPMSMSMetadataDTO) {
    this.iCPMSMSMetadataDTO = iCPMSMSMetadataDTO;
    return this;
  }

   /**
   * Get iCPMSMSMetadataDTO
   * @return iCPMSMSMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public ICPMSMSMetadataDTO getICPMSMSMetadataDTO() {
    return iCPMSMSMetadataDTO;
  }

  public void setICPMSMSMetadataDTO(ICPMSMSMetadataDTO iCPMSMSMetadataDTO) {
    this.iCPMSMSMetadataDTO = iCPMSMSMetadataDTO;
  }

  public ICPMSLithoDTO iCPMSMetadataDTO(ICPMSMetadataDTO iCPMSMetadataDTO) {
    this.iCPMSMetadataDTO = iCPMSMetadataDTO;
    return this;
  }

   /**
   * Get iCPMSMetadataDTO
   * @return iCPMSMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public ICPMSMetadataDTO getICPMSMetadataDTO() {
    return iCPMSMetadataDTO;
  }

  public void setICPMSMetadataDTO(ICPMSMetadataDTO iCPMSMetadataDTO) {
    this.iCPMSMetadataDTO = iCPMSMetadataDTO;
  }

  public ICPMSLithoDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ICPMSLithoDTO laserMetadataDTO(LaserMetadataDTO laserMetadataDTO) {
    this.laserMetadataDTO = laserMetadataDTO;
    return this;
  }

   /**
   * Get laserMetadataDTO
   * @return laserMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public LaserMetadataDTO getLaserMetadataDTO() {
    return laserMetadataDTO;
  }

  public void setLaserMetadataDTO(LaserMetadataDTO laserMetadataDTO) {
    this.laserMetadataDTO = laserMetadataDTO;
  }

  public ICPMSLithoDTO mCICPMSMetadataDTO(MCICPMSMetadataDTO mCICPMSMetadataDTO) {
    this.mCICPMSMetadataDTO = mCICPMSMetadataDTO;
    return this;
  }

   /**
   * Get mCICPMSMetadataDTO
   * @return mCICPMSMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public MCICPMSMetadataDTO getMCICPMSMetadataDTO() {
    return mCICPMSMetadataDTO;
  }

  public void setMCICPMSMetadataDTO(MCICPMSMetadataDTO mCICPMSMetadataDTO) {
    this.mCICPMSMetadataDTO = mCICPMSMetadataDTO;
  }

  public ICPMSLithoDTO qICPMSMetadataDTO(QICPMSMetadataDTO qICPMSMetadataDTO) {
    this.qICPMSMetadataDTO = qICPMSMetadataDTO;
    return this;
  }

   /**
   * Get qICPMSMetadataDTO
   * @return qICPMSMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public QICPMSMetadataDTO getQICPMSMetadataDTO() {
    return qICPMSMetadataDTO;
  }

  public void setQICPMSMetadataDTO(QICPMSMetadataDTO qICPMSMetadataDTO) {
    this.qICPMSMetadataDTO = qICPMSMetadataDTO;
  }

  public ICPMSLithoDTO solutionOtherMetadataDTO(SolutionOtherMetadataDTO solutionOtherMetadataDTO) {
    this.solutionOtherMetadataDTO = solutionOtherMetadataDTO;
    return this;
  }

   /**
   * Get solutionOtherMetadataDTO
   * @return solutionOtherMetadataDTO
  **/
  @ApiModelProperty(value = "")
  public SolutionOtherMetadataDTO getSolutionOtherMetadataDTO() {
    return solutionOtherMetadataDTO;
  }

  public void setSolutionOtherMetadataDTO(SolutionOtherMetadataDTO solutionOtherMetadataDTO) {
    this.solutionOtherMetadataDTO = solutionOtherMetadataDTO;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ICPMSLithoDTO icPMSLithoDTO = (ICPMSLithoDTO) o;
    return Objects.equals(this.hRICPMSMetadataDTO, icPMSLithoDTO.hRICPMSMetadataDTO) &&
        Objects.equals(this.iCPMSMSMetadataDTO, icPMSLithoDTO.iCPMSMSMetadataDTO) &&
        Objects.equals(this.iCPMSMetadataDTO, icPMSLithoDTO.iCPMSMetadataDTO) &&
        Objects.equals(this.id, icPMSLithoDTO.id) &&
        Objects.equals(this.laserMetadataDTO, icPMSLithoDTO.laserMetadataDTO) &&
        Objects.equals(this.mCICPMSMetadataDTO, icPMSLithoDTO.mCICPMSMetadataDTO) &&
        Objects.equals(this.qICPMSMetadataDTO, icPMSLithoDTO.qICPMSMetadataDTO) &&
        Objects.equals(this.solutionOtherMetadataDTO, icPMSLithoDTO.solutionOtherMetadataDTO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hRICPMSMetadataDTO, iCPMSMSMetadataDTO, iCPMSMetadataDTO, id, laserMetadataDTO, mCICPMSMetadataDTO, qICPMSMetadataDTO, solutionOtherMetadataDTO);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ICPMSLithoDTO {\n");
    
    sb.append("    hRICPMSMetadataDTO: ").append(toIndentedString(hRICPMSMetadataDTO)).append("\n");
    sb.append("    iCPMSMSMetadataDTO: ").append(toIndentedString(iCPMSMSMetadataDTO)).append("\n");
    sb.append("    iCPMSMetadataDTO: ").append(toIndentedString(iCPMSMetadataDTO)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    laserMetadataDTO: ").append(toIndentedString(laserMetadataDTO)).append("\n");
    sb.append("    mCICPMSMetadataDTO: ").append(toIndentedString(mCICPMSMetadataDTO)).append("\n");
    sb.append("    qICPMSMetadataDTO: ").append(toIndentedString(qICPMSMetadataDTO)).append("\n");
    sb.append("    solutionOtherMetadataDTO: ").append(toIndentedString(solutionOtherMetadataDTO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

